#!/bin/bash

# This is a thin wrapper around Testcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using Testcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_TestcoinD

# Grab the value of $REAL_TestcoinCLI which may be Testcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_TestcoinCLI}" "$@" | sed 's/\r//'
